version: '3'
services:
  redis:
      image: redis
      container_name: redis_example
      ports:
        - "6379:6379"
  app:
    container_name: app_example
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes: 
      - ./:/var/www
  web:  
    container_name: web_example 
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on: 
      - app
      - postgres
      - redis
  postgres:
    container_name: postgre_example
    image: postgres:10.3
    volumes:
      - pgdata:/var/lib/postgres
    environment:
        - POSTGRES_DB=exampledb
        - POSTGRES_USER=nora
        - POSTGRES_PASSWORD=secret
    ports:
        - "54320:5432"

volumes:
  pgdata: